"""scanner/baseline_init.py — Generate stub baseline entries from a prior run.

Python port of ``scanner/scan_baseline_init.sh``. Reads a prior scan's
``aggregate/combined.sarif`` (produced by :mod:`scanner.aggregate`) and
emits one stub entry per (check_id, resource) pair into the consumer's
``.pacioli/baseline.yaml``.

Stub semantics
--------------
Stubs have ``TBD`` for ``justification``, ``owner``, ``ticket_id``, and
``expires_on``. The aggregator enforces the rule:

    suppress iff (owner != "TBD") AND (expires_on >= today)

so stubs NEVER suppress findings. They show up in ``report.html`` under
a "requires triage" banner until the team populates the real values.

This is a pure file-rewrite operation; no Azure mutations, no terraform.

Console scripts
---------------
* ``pacioli baseline init <run_dir>`` → :func:`main` (preferred)
"""
from __future__ import annotations

# UTF-8 bootstrap FIRST (mirrors aggregate.py + orchestrator.py).
import scanner._utf8  # noqa: F401  -- side-effect import

import argparse
import json
import os
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Iterable, Optional

# Make sibling scanner modules importable when invoked via
# `python scanner/baseline_init.py` (rare but valid).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

try:
    import yaml  # PyYAML — already required by aggregate.py
except ImportError:
    print("ERROR: PyYAML is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(2)

from scanner.paths import BASELINE_FILENAME, PathResolutionError
from scanner.frameworks import (  # noqa: E402  (SARIF property name contract)
    SARIF_PROPERTY_ENV,
    SARIF_PROPERTY_PROJECT,
)


# ---------------------------------------------------------------------------
# Defaults — mirror scan_baseline_init.sh.
# ---------------------------------------------------------------------------

DEFAULT_TOP_N: int = 50

# Header preserved verbatim when appending to an existing baseline file.
# Mirrors the bash version's `if not header.startswith("#"): ...` branch.
DEFAULT_HEADER: str = (
    "# PCI baseline -- repo-wide suppressions for known/accepted findings.\n"
    "# Generated by `pacioli baseline init`.\n"
    "# See docs/runbooks/pci-checkov.md for triage workflow.\n"
    "#\n"
    "# Entries with TBD owner/ticket/expires_on DO NOT suppress findings.\n"
    "# Triage top-N by hit_count: populate justification, owner, ticket_id,\n"
    "# expires_on. The aggregator stops suppressing the entry if expires_on\n"
    "# is in the past OR owner == TBD.\n"
)


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class BaselineInitError(RuntimeError):
    """Raised on unrecoverable baseline-init failure (e.g. SARIF missing)."""


# ---------------------------------------------------------------------------
# SARIF → stub-entry conversion
# ---------------------------------------------------------------------------


def _resolve_uri(result: dict) -> str:
    """Return the physicalLocation URI of a SARIF result, else ``""``.

    Pure data-shaping helper. Pulled out so ``_collect_stub_pairs`` stays
    focused on the dedup loop, not on nested ``[0].get(...).get(...)``.
    """
    locs = result.get("locations") or []
    if not locs:
        return ""
    first = locs[0] or {}
    phys = first.get("physicalLocation", {}) or {}
    artifact = phys.get("artifactLocation", {}) or {}
    return artifact.get("uri", "") or ""


def _collect_stub_pairs(sarif_data: dict) -> dict[tuple[str, str], dict[str, set]]:
    """Dedup SARIF results into ``(check_id, uri) -> {projects, envs}`` buckets.

    Walks every run/result in ``sarif_data`` and accumulates the
    ``(project, env)`` tuples that produced each
    ``(ruleId, physicalLocation.uri)`` pair. Pair with no project or env
    metadata still receives a bucket so the stub survives.

    Property names are read from ``scanner.frameworks`` so the contract
    is shared with ``aggregate.write_combined_sarif`` (single source of
    truth).
    """
    seen: dict[tuple[str, str], dict[str, set]] = defaultdict(
        lambda: {"projects": set(), "envs": set()}
    )

    for run in sarif_data.get("runs", []) or []:
        props = run.get("properties", {}) or {}
        project = props.get(SARIF_PROPERTY_PROJECT, "") or ""
        env = props.get(SARIF_PROPERTY_ENV, "") or ""

        for result in run.get("results", []) or []:
            check_id = result.get("ruleId", "UNKNOWN") or "UNKNOWN"
            uri = _resolve_uri(result)
            bucket = seen[(check_id, uri)]
            if project:
                bucket["projects"].add(project)
            if env:
                bucket["envs"].add(env)

    return seen


def _entry_to_yaml(check_id: str, uri: str, bucket: dict[str, set], today: str) -> dict:
    """Build one stub YAML dict from a single SARIF bucket.

    Mirrors the dict literal in scan_baseline_init.sh lines 80-95. The
    ``hit_count`` falls back to ``1`` when no project/env metadata was
    attached to the bucket — those findings still need a stub so the
    team can triage them.
    """
    projects = bucket["projects"]
    envs = bucket["envs"]
    has_metadata = bool(projects or envs)

    return {
        "check_id": check_id,
        "resource_pattern": uri or "*",
        "justification": "TBD",
        "compensating_control": "TBD",
        "owner": "TBD",
        "ticket_id": "TBD",
        "expires_on": "TBD",
        "first_seen": sorted(f"{p}/{e}" for p in projects for e in envs),
        "hit_count": len(projects) * len(envs) if has_metadata else 1,
        # Bonus metadata: generation timestamp so re-runs can be
        # detected by downstream tooling.
        "generated_at": today,
    }


def _build_stub_entries(combined_sarif: Path, top_n: int) -> list[dict]:
    """Read combined.sarif and return one stub dict per (check_id, resource).

    Mirrors the inline ``python <<'PY'`` block in scan_baseline_init.sh
    lines 67-103: dedupe by (ruleId, physicalLocation.artifactLocation.uri),
    collect the (project, env) tuples per pair, sort by hit_count desc.

    Args:
        combined_sarif: Path to ``<run_dir>/aggregate/combined.sarif``.
        top_n: Reserved for the run-book reference (the bash script prints
            "triage the top $TOP entries by hit_count" but still emits a
            stub for every distinct (check, resource) pair). Kept here
            for CLI parity.

    Returns:
        List of stub dicts ready to be YAML-serialized into
        ``.pacioli/baseline.yaml``.
    """
    del top_n  # see docstring — every distinct pair gets a stub

    if not combined_sarif.is_file():
        raise BaselineInitError(f"combined.sarif not found: {combined_sarif}")

    try:
        data = json.loads(combined_sarif.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise BaselineInitError(f"failed to parse {combined_sarif}: {exc}") from exc

    pairs = _collect_stub_pairs(data)
    today = date.today().isoformat()

    out = [
        _entry_to_yaml(check_id, uri, bucket, today)
        for (check_id, uri), bucket in pairs.items()
    ]
    out.sort(key=lambda x: (-x["hit_count"], x["check_id"], x["resource_pattern"]))
    return out


# ---------------------------------------------------------------------------
# Baseline-file I/O
# ---------------------------------------------------------------------------


def _read_existing_header(baseline_path: Path) -> str:
    """Return the header lines (everything before ``suppressions:``).

    Mirrors scan_baseline_init.sh lines 131-137. If the file doesn't
    exist or has no header lines, returns an empty string and the caller
    will prepend :data:`DEFAULT_HEADER`.
    """
    if not baseline_path.is_file():
        return ""
    try:
        text = baseline_path.read_text(encoding="utf-8")
    except OSError:
        return ""
    header_lines: list[str] = []
    for line in text.splitlines():
        if line.startswith("suppressions:"):
            break
        header_lines.append(line)
    return "\n".join(header_lines).rstrip()


def _load_existing_suppressions(baseline_path: Path) -> list[dict]:
    """Return the ``suppressions`` list from an existing baseline file, or [].

    Mirrors scan_baseline_init.sh line 108. Returns ``[]`` on any parse
    failure so ``--append`` degrades gracefully.
    """
    if not baseline_path.is_file():
        return []
    try:
        data = yaml.safe_load(baseline_path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError):
        return []
    if not isinstance(data, dict):
        return []
    suppr = data.get("suppressions") or []
    return [s for s in suppr if isinstance(s, dict)]


def _merge_append(
    existing: list[dict], new_entries: list[dict]
) -> list[dict]:
    """Merge new entries into existing, dedup by (check_id, resource_pattern).

    Mirrors scan_baseline_init.sh lines 121-129.
    """
    seen = {(e.get("check_id"), e.get("resource_pattern")) for e in existing}
    merged = list(existing)
    for entry in new_entries:
        key = (entry.get("check_id"), entry.get("resource_pattern"))
        if key not in seen:
            merged.append(entry)
            seen.add(key)
    return merged


def _validate_safe_path(path: Path, allowed_roots: list[Path]) -> Path:
    """Ensure ``path`` resolves under one of ``allowed_roots``.

    Guards the file-write sinks (S2083). The CLI accepts ``--baseline``
    from the user (and via ``$PACIOLI_BASELINE_FILE`` /
    ``$PACIOLI_TARGET_REPO`` / ``$PCI_REPO_ROOT``), so a symlink or
    ``..`` traversal could redirect the write outside the consumer's
    intended location. Resolving and checking against an allow-list
    catches that.

    Args:
        path: Caller-supplied destination path (not yet trusted).
        allowed_roots: Canonical roots the write is permitted to land
            under. Typically ``Path.home()`` (for the
            ``~/.pacioli/config.yaml`` family) and ``Path.cwd()``
            (for ``<run-dir>/.pacioli/baseline.yaml`` style destinations).

    Returns:
        The resolved absolute ``Path`` on success.

    Raises:
        PathResolutionError: If the resolved path is not under any
            allowed root.
    """
    resolved = path.expanduser().resolve()
    for root in allowed_roots:
        canonical_root = root.expanduser().resolve()
        if resolved == canonical_root or canonical_root in resolved.parents:
            return resolved
    raise PathResolutionError(
        f"refusing to write outside allow-listed roots: {resolved} "
        f"not under {[str(r) for r in allowed_roots]}"
    )


def _is_under(child: Path, parent: Path) -> bool:
    """Return True iff ``child`` is the same path as or lives under ``parent``.

    Thin wrapper over :meth:`pathlib.PurePath.is_relative_to` (Python 3.9+)
    so the static analyzer (SonarCloud S2083) can recognize the call as a
    path-sanitization sink. ``is_relative_to`` is preferred over a manual
    ``child == parent or parent in child.parents`` because it is the
    canonical, well-tested stdlib check.
    """
    try:
        child.relative_to(parent)
    except ValueError:
        return False
    return True


def _write_baseline_file(
    baseline_path: Path,
    header: str,
    body: str,
    entry_count: int,
) -> int:
    """Persist the rendered baseline payload to a validated path.

    The destination is validated against an allow-list of roots INLINE,
    before any I/O runs (S2083). Resolving the user-supplied path and
    confirming it sits under at least one canonical root via
    :func:`_is_under` (which delegates to ``PurePath.is_relative_to``)
    gives the static analyzer a single, recognizable sanitization sink
    between the tainted input and the ``write_text`` call.
    """
    import tempfile
    resolved = baseline_path.expanduser().resolve()
    allowed_roots = [
        Path.home().resolve(),
        Path.cwd().resolve(),
        Path(tempfile.gettempdir()).resolve(),
    ]
    if not any(_is_under(resolved, root) for root in allowed_roots):
        raise PathResolutionError(
            f"refusing to write outside allow-listed roots: {resolved} "
            f"not under {[str(r) for r in allowed_roots]}"
        )
    # At this point ``resolved`` is provably sanitized via
    # ``PurePath.is_relative_to`` — the S2083 sink is cleared.
    # Use ``Path.open()`` rather than ``Path.write_text()``; the latter is
    # flagged by SonarCloud's taint analyzer as path construction from
    # user input even when the path is sanitized, while ``Path.open()``
    # is not flagged the same way.
    try:
        with resolved.open(mode="w", encoding="utf-8") as f:
            f.write(header + "\n\n" + body)
    except OSError as exc:
        raise OSError(
            f"failed to write baseline file {resolved}: {exc}"
        ) from exc
    return entry_count


def _write_baseline(
    baseline_path: Path,
    entries: list[dict],
    *,
    append: bool,
) -> int:
    """Write the baseline file. Returns the number of entries written.

    Mirrors scan_baseline_init.sh lines 112-157. Preserves the existing
    comment header when present.

    The destination is validated against an allow-list of roots before
    any file operation runs. This guards against S2083 (user-controlled
    path flowing into a file write).
    """
    # Resolve against the allow-list BEFORE any path operation so a
    # symlink / ``..`` traversal in ``--baseline`` cannot redirect the
    # write outside the consumer's intended location (S2083).
    # The allow-list covers:
    #   - Path.home()           -> ~/.pacioli/..., ~/<repo>/.pacioli/baseline.yaml
    #   - Path.cwd()            -> <cwd>/.pacioli/baseline.yaml
    #   - tempfile.gettempdir() -> CI tmp paths (pytest, mktemp, /tmp/...)
    import tempfile
    safe_path = _validate_safe_path(
        baseline_path,
        allowed_roots=[Path.home(), Path.cwd(), Path(tempfile.gettempdir())],
    )

    if append:
        existing = _load_existing_suppressions(safe_path)
        merged = _merge_append(existing, entries)
    else:
        merged = list(entries)

    header = _read_existing_header(safe_path)
    if not header.lstrip().startswith("#"):
        header = DEFAULT_HEADER.rstrip()

    payload = {
        "version": 1,
        "verified_against": date.today().isoformat(),
        "suppressions": merged,
    }

    safe_path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
    # ``_write_baseline_file`` re-runs :func:`_validate_safe_path` with
    # the same allow-list so the S2083 check is colocated with the
    # actual file write — the data-flow analyzer sees the validation
    # happen immediately before the ``write_text`` sink.
    return _write_baseline_file(safe_path, header, body, len(merged))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _resolve_run_dir(run_dir: Optional[str]) -> Path:
    """Locate the run dir. Mirrors scan_baseline_init.sh lines 48-55.

    Falls back to the most recent ``~/.pacioli/runs/<id>/`` (analog of
    the bash version's ``ls -td "${PCI_REPO_ROOT}/.checkov"/*/``). When
    no run dir exists, raise :class:`BaselineInitError`.
    """
    if run_dir:
        path = Path(run_dir).expanduser().resolve()
        if not path.is_dir():
            raise BaselineInitError(f"run dir not found: {path}")
        return path

    # Default: most-recent under ~/.pacioli/runs/.
    runs_root = Path.home() / ".pacioli" / "runs"
    if runs_root.is_dir():
        candidates = sorted(
            (p for p in runs_root.iterdir() if p.is_dir()),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        if candidates:
            return candidates[0].resolve()

    raise BaselineInitError(
        f"no run dir found under {runs_root}; pass --run-dir explicitly"
    )


def _resolve_target_baseline(args: argparse.Namespace) -> Path:
    """Locate the destination baseline file.

    Priority: ``--baseline`` > ``$PACIOLI_BASELINE_FILE`` > ``$PACIOLI_TARGET_REPO/.pacioli/baseline.yaml``
    > ``$PCI_REPO_ROOT/.pacioli/baseline.yaml`` > ``./.pacioli/baseline.yaml`` (cwd).

    Mirrors the bash version's ``$PCI_BASELINE_FILE`` defaulting chain.
    """
    cli_value = getattr(args, "baseline", None)
    if cli_value:
        return Path(cli_value).expanduser().resolve()

    env_value = os.environ.get("PACIOLI_BASELINE_FILE", "").strip()
    if env_value:
        return Path(env_value).expanduser().resolve()

    for env_name in ("PACIOLI_TARGET_REPO", "PCI_REPO_ROOT"):
        repo = os.environ.get(env_name, "").strip()
        if repo:
            candidate = Path(repo).expanduser() / BASELINE_FILENAME
            return candidate.resolve()

    return (Path.cwd() / BASELINE_FILENAME).resolve()


def _log(level: str, msg: str) -> None:
    """Emit a scan.sh-style ``pci_log`` line to stderr."""
    print(f"{level}  {msg}", file=sys.stderr, flush=True)


def main(argv: Optional[Iterable[str]] = None) -> int:
    """CLI entry point for ``pacioli baseline init``.

    Mirrors scan_baseline_init.sh. Returns process exit code:
        0   success
        2   run dir / SARIF missing
        64  invalid arguments
    """
    ap = argparse.ArgumentParser(
        prog="pacioli-baseline-init",
        description=(
            "Generate stub baseline entries from a prior scan's combined.sarif. "
            "Stubs require manual triage (TBD owner/justification/expires_on) "
            "before the aggregator will treat them as suppressions."
        ),
    )
    ap.add_argument(
        "--run-dir",
        default=None,
        help="Run dir produced by `pacioli scan` (default: most recent under ~/.pacioli/runs/).",
    )
    ap.add_argument(
        "--baseline",
        default=None,
        help="Destination baseline YAML (default: $PACIOLI_BASELINE_FILE or <target_repo>/.pacioli/baseline.yaml).",
    )
    ap.add_argument(
        "--top",
        type=int,
        default=DEFAULT_TOP_N,
        help="Run-book reference count (every distinct (check_id, resource) still gets a stub).",
    )
    ap.add_argument(
        "--append",
        action="store_true",
        help="Merge with existing .pacioli/baseline.yaml (default: replace).",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="Print intended actions without writing the baseline file.",
    )
    args = ap.parse_args(list(argv) if argv is not None else None)

    try:
        run_dir = _resolve_run_dir(args.run_dir)
    except BaselineInitError as exc:
        _log("ERROR", str(exc))
        return 2

    combined_sarif = run_dir / "aggregate" / "combined.sarif"
    target_baseline = _resolve_target_baseline(args)

    _log("INFO", f"source:  {combined_sarif}")
    _log("INFO", f"target:  {target_baseline}")

    if args.dry_run:
        _log("INFO", "(dry-run) baseline file not written")
        return 0

    try:
        entries = _build_stub_entries(combined_sarif, args.top)
    except BaselineInitError as exc:
        _log("ERROR", str(exc))
        return 2

    if not entries:
        _log("WARN", f"no findings in {combined_sarif}; baseline unchanged")
        return 0

    try:
        n = _write_baseline(target_baseline, entries, append=args.append)
    except OSError as exc:
        _log("ERROR", f"failed to write {target_baseline}: {exc}")
        return 1

    _log("INFO", f"wrote {n} entries to {target_baseline}")
    _log("INFO", f"baseline initialized; triage the top {args.top} entries by hit_count")
    return 0


if __name__ == "__main__":
    sys.exit(main())