"""scanner/config_bootstrap.py -- Interactive scope+baseline scaffold for first-time users.

Auto-creates ``pci_scope.yaml`` and ``pci_baseline.yaml`` when missing, mirroring the
mapping picker pattern. Reuses :func:`scanner.discovery.discover_pairs` for framework-
agnostic IaC discovery. Reuses :func:`scanner.baseline_init._validate_safe_path` and
:func:`scanner.baseline_init._is_under` for S2083-safe writes. Never overwrites
existing files.

Interaction model
-----------------

The CLI dispatcher calls :func:`is_bootstrap_interactive` to decide whether the
interactive prompt may run. When interactive, :func:`prompt_and_create` prints a
``Y/n`` prompt; when non-interactive, :func:`auto_create` writes silently. Both
respect the "never overwrite" contract: existing files are always skipped.

Discovery model
---------------

:func:`render_scope_yaml` calls :func:`scanner.discovery.discover_pairs` and groups
the returned ``(project, env)`` pairs into the ``projects:`` list of the scope YAML.
When the target repo is empty (``NoIaCFoundError``), the scope falls back to
``scan_paths: [{path: "."}]`` so the user can still run a scan.

Safety model
------------

Every file write goes through :func:`scanner.baseline_init._validate_safe_path`
with an allow-list of ``Path.home()``, ``Path.cwd()``, and the temp directory,
matching the pattern established by :func:`scanner.baseline_init._write_baseline_file`.
This guards against S2083 (user-controlled path flowing into a file write).
"""

from __future__ import annotations

# UTF-8 bootstrap FIRST (mirrors baseline_init.py + aggregate.py).
import scanner._utf8  # noqa: F401  -- side-effect import

import argparse
import os
import sys
import tempfile
from datetime import date
from pathlib import Path
from typing import Optional

import yaml

from scanner.baseline_init import _validate_safe_path, _is_under
from scanner.discovery import discover_pairs, SCOPE_FILENAME, _parse_scope_manifest, NoIaCFoundError


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Truthy values treated as "non-interactive" for PACIOLI_NON_INTERACTIVE / CI.
#: Mirrors :data:`scanner.mapping_picker._TRUTHY_ENV` so the gate semantics
#: are identical across both interactive modules.
_TRUTHY_ENV: frozenset[str] = frozenset({"1", "true", "yes", "on"})

#: Filename for the scope manifest. Re-exported from :mod:`scanner.discovery`
#: so callers can import everything from this module without reaching into
#: discovery internals.
SCOPE_FILENAME = SCOPE_FILENAME  # noqa: F821  -- re-exported constant from discovery

#: Filename for the baseline manifest.
BASELINE_FILENAME: str = "pci_baseline.yaml"


# ---------------------------------------------------------------------------
# Comment headers
# ---------------------------------------------------------------------------

_SCOPE_HEADER: str = (
    "# Pacioli scope manifest -- declares which IaC projects/environments are in scope.\n"
    "#\n"
    "# Schema:\n"
    "#   projects:   list of project records (each with project, description, status, envs)\n"
    "#   envs:       list of env records (each with name, status, reason)\n"
    "#   scan_paths: explicit stack-root entries (alternative to projects:)\n"
    "#\n"
    "# Status values: in_scope, pending, excluded. Pending/excluded require a reason.\n"
    "#\n"
    "# Example -- in_scope project with in_scope env:\n"
    "# projects:\n"
    "#   - project: myapp\n"
    "#     description: My application infrastructure\n"
    "#     status: in_scope\n"
    "#     envs:\n"
    "#       - name: prod\n"
    "#         status: in_scope\n"
    "#\n"
    "# Example -- pending env (not scanned until triaged):\n"
    "#       - name: staging\n"
    "#         status: pending\n"
    "#         reason: Awaiting Security approval.\n"
    "#\n"
    "# Next steps:\n"
    "#   1. Edit this file to set status=in_scope for what you want scanned\n"
    "#   2. Set status=pending or excluded with a reason for the rest\n"
    "#   3. Run `pacioli scan` again\n"
)

_BASELINE_HEADER: str = (
    "# Pacioli baseline -- repo-wide suppressions for known/accepted findings.\n"
    "# Generated by `pacioli scan --init` (or the interactive prompt).\n"
    "#\n"
    "# Schema:\n"
    "#   version:          schema version (always 1)\n"
    "#   verified_against: ISO date when this file was generated\n"
    "#   suppressions:     list of suppression entries (empty by default)\n"
    "#\n"
    "# Each suppression entry:\n"
    "#   check_id, resource_pattern, justification, compensating_control,\n"
    "#   owner, ticket_id, expires_on\n"
    "#\n"
    "# The aggregator suppresses ONLY if expires_on >= today AND owner != \"TBD\".\n"
    "# Stubs (TBD*) NEVER suppress findings -- they'll appear in report.html as\n"
    "# \"requires triage\" until you populate the real values.\n"
    "#\n"
    "# Example -- populate after first scan via `pacioli baseline init`:\n"
    "# suppressions:\n"
    "#   - check_id: CKV_AZURE_59\n"
    "#     resource_pattern: \"azurerm_storage_account.example\"\n"
    "#     justification: \"Legacy resource, migration planned\"\n"
    "#     compensating_control: \"WAF rule abc123\"\n"
    "#     owner: \"team@example.com\"\n"
    "#     ticket_id: \"TICKET-123\"\n"
    "#     expires_on: \"2026-12-31\"\n"
    "#\n"
    "# Next steps:\n"
    "#   1. Run `pacioli scan` to generate findings\n"
    "#   2. Run `pacioli baseline init <run_dir>` to seed stub suppressions\n"
    "#   3. Triage top-stubs by hit_count and populate the 7 fields\n"
)


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class ScopeInitError(RuntimeError):
    """Raised on unrecoverable scaffolding failure."""


# ---------------------------------------------------------------------------
# Env helpers (mirror scanner.mapping_picker._is_truthy_env)
# ---------------------------------------------------------------------------


def _is_truthy_env(name: str) -> bool:
    """Return True when env var ``name`` is set to a truthy value.

    Mirrors :func:`scanner.mapping_picker._is_truthy_env` so the
    non-interactive gate is consistent across both interactive modules.
    """
    value = os.environ.get(name)
    if value is None:
        return False
    return value.strip().lower() in _TRUTHY_ENV


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def is_bootstrap_interactive(args: argparse.Namespace) -> bool:
    """Return True when the bootstrap prompt is allowed to run.

    Mirrors :func:`scanner.mapping_picker.is_interactive` but WITHOUT the
    "no packs installed" check -- we ALWAYS check for config files (even
    if no mapping packs exist).

    Returns False when ANY of the following is true:

    * ``args.non_interactive`` is True (``--non-interactive`` flag).
    * ``PACIOLI_NON_INTERACTIVE`` is set to a truthy value.
    * ``CI`` is set to a truthy value (covers GitHub Actions, Azure
      DevOps, GitLab CI, CircleCI, etc.).
    * ``sys.stdin.isatty()`` returns False.

    Returns True otherwise.
    """
    if getattr(args, "non_interactive", False):
        return False
    if _is_truthy_env("PACIOLI_NON_INTERACTIVE"):
        return False
    if _is_truthy_env("CI"):
        return False
    try:
        is_tty = sys.stdin.isatty()
    except (AttributeError, ValueError):
        is_tty = False
    if not is_tty:
        return False
    return True


def missing_config_files(target_repo: Path) -> tuple[Optional[Path], Optional[Path]]:
    """Return ``(scope_path, baseline_path)`` with ``None`` for files that exist.

    Tuple semantics:

    * ``(None, None)`` -- both files exist (nothing to scaffold).
    * ``(scope_path, None)`` -- only the baseline exists.
    * ``(None, baseline_path)`` -- only the scope exists.
    * ``(scope_path, baseline_path)`` -- both missing.

    The returned paths are the *would-be* locations under ``target_repo``;
    they are always ``target_repo / SCOPE_FILENAME`` and
    ``target_repo / BASELINE_FILENAME`` respectively. Callers should
    re-check ``.is_file()`` before writing to honour the "never
    overwrite" contract.
    """
    target_repo = Path(target_repo)
    scope_path = target_repo / SCOPE_FILENAME
    baseline_path = target_repo / BASELINE_FILENAME
    scope_missing = scope_path if not scope_path.is_file() else None
    baseline_missing = baseline_path if not baseline_path.is_file() else None
    return (scope_missing, baseline_missing)


def render_scope_yaml(target_repo: Path) -> str:
    """Render a ``pci_scope.yaml`` string auto-discovered from ``target_repo``.

    Handles three layouts:

    1. **env/ tree**: ``discover_pairs`` returns multiple ``(project, env)``
       pairs; they are grouped by project into structured records.
    2. **flat repo**: ``discover_pairs`` returns ``[("default", "default")]``;
       the scope contains one project with one env.
    3. **empty repo**: ``discover_pairs`` raises :class:`NoIaCFoundError`;
       the scope falls back to ``scan_paths: [{path: "."}]`` so the user
       can still run a scan against the repo root.

    All discovered pairs are emitted with ``status: in_scope``. The user
    can later edit the file to set ``pending`` or ``excluded`` for
    environments they want to gate.

    The output YAML is valid against
    :func:`scanner.discovery._parse_scope_manifest`.
    """
    target_repo = Path(target_repo)
    try:
        pairs = discover_pairs(target_repo)
    except NoIaCFoundError:
        pairs = []

    if pairs:
        # Group (project, env) pairs by project name, preserving
        # deterministic order (sorted) so re-runs produce identical files.
        projects_map: dict[str, list[str]] = {}
        for pair in pairs:
            projects_map.setdefault(pair.project, []).append(pair.env)

        projects: list[dict] = []
        for project_name in sorted(projects_map):
            env_names = sorted(projects_map[project_name])
            envs = [{"name": e, "status": "in_scope"} for e in env_names]
            projects.append({
                "project": project_name,
                "description": f"Auto-discovered project {project_name}",
                "status": "in_scope",
                "envs": envs,
            })
        payload: dict = {"projects": projects}
    else:
        # Empty repo: fall back to a single scan_paths entry pointing
        # at the repo root. This lets the user run `pacioli scan .`
        # immediately without editing the file.
        payload = {"scan_paths": [{"path": "."}]}

    body = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
    return _SCOPE_HEADER + "\n" + body


def render_baseline_yaml() -> str:
    """Render an empty ``pci_baseline.yaml`` with rich comment header + 1 example.

    Returns a YAML string with the shape::

        version: 1
        verified_against: <today>
        suppressions: []

    plus a comment header showing the schema and one commented-out
    example suppression entry.
    """
    payload = {
        "version": 1,
        "verified_against": date.today().isoformat(),
        "suppressions": [],
    }
    body = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
    return _BASELINE_HEADER + "\n" + body


def _safe_write(path: Path, content: str) -> bool:
    """Write ``content`` to ``path`` via ``_validate_safe_path`` (S2083-safe).

    Returns True on success, False on OSError (logged as WARN, never raised).
    The caller (``auto_create``) uses this to honour the "never crash the
    scan because a config write failed" contract.
    """
    allowed_roots = [Path.home(), Path.cwd(), Path(tempfile.gettempdir())]
    try:
        safe_path = _validate_safe_path(path, allowed_roots=allowed_roots)
    except Exception:
        # Path validation failure -- log and skip.
        print(f"WARN  config_bootstrap: refusing to write outside allow-listed roots: {path}",
              file=sys.stderr, flush=True)
        return False

    safe_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        with safe_path.open(mode="w", encoding="utf-8") as f:
            f.write(content)
    except OSError as exc:
        print(f"WARN  config_bootstrap: failed to write {safe_path}: {exc}",
              file=sys.stderr, flush=True)
        return False
    return True


def auto_create(
    args: argparse.Namespace,
    target_repo: Path,
    scope_path: Optional[Path],
    baseline_path: Optional[Path],
) -> list[Path]:
    """Auto-create missing config files without prompting.

    Skips files that already exist (never overwrites). Returns a list of
    paths actually written. Uses :func:`_validate_safe_path` for S2083-safe
    writes via :func:`_safe_write`.

    Args:
        args: The parsed CLI namespace (unused but kept for signature
            symmetry with :func:`prompt_and_create`).
        target_repo: The target repo root (used for scope discovery).
        scope_path: Path where the scope file should be written, or
            ``None`` when the scope already exists.
        baseline_path: Path where the baseline file should be written,
            or ``None`` when the baseline already exists.

    Returns:
        List of :class:`~pathlib.Path` objects for files actually written.
    """
    written: list[Path] = []

    if scope_path is not None and not scope_path.is_file():
        content = render_scope_yaml(target_repo)
        if _safe_write(scope_path, content):
            written.append(scope_path)

    if baseline_path is not None and not baseline_path.is_file():
        content = render_baseline_yaml()
        if _safe_write(baseline_path, content):
            written.append(baseline_path)

    return written


def prompt_and_create(
    args: argparse.Namespace,
    target_repo: Path,
    scope_path: Optional[Path],
    baseline_path: Optional[Path],
) -> list[Path]:
    """Interactive ``Y/n`` prompt to create missing config files.

    * ``y``, ``yes``, ``""`` (default) -> create via :func:`auto_create`.
    * ``n``, ``no`` -> no-op (returns ``[]``).
    * ``EOFError``, ``KeyboardInterrupt`` -> no-op (returns ``[]``).

    The prompt text uses ``input()`` (no rich/textual/prompt_toolkit).
    """
    try:
        yn = input("Create missing config files? [Y/n]: ")
    except (EOFError, KeyboardInterrupt):
        return []

    if yn.strip().lower() in ("n", "no"):
        return []

    return auto_create(args, target_repo, scope_path, baseline_path)


__all__ = [
    "ScopeInitError",
    "is_bootstrap_interactive",
    "missing_config_files",
    "render_scope_yaml",
    "render_baseline_yaml",
    "auto_create",
    "prompt_and_create",
    "SCOPE_FILENAME",
    "BASELINE_FILENAME",
]
