#!/usr/bin/env bash
# scan_pci_baseline_init.sh — Generate stub baseline entries from a run.
#
# Reads a prior scan's combined.sarif (produced by aggregate.py) and
# emits one stub entry per finding into pci_baseline.yaml. Stubs have
# TBD for justification/owner/ticket_id/expires_on; the team triages
# top-N by count * severity_weight to populate the real values.
#
# Stub entries NEVER suppress findings (the aggregator enforces
# `owner != TBD AND expires_on >= today`). They show up in report.html
# as "requires triage" until populated.
#
# Usage:
#   scan_pci_baseline_init.sh [--run-dir <dir>] [--top <N>] [--append]
#
# Defaults:
#   --run-dir  .checkov/<most-recent>/
#   --top      50  (only show top-by-priority in the run book; but ALL
#                   findings get a stub entry)
#   --append   merge with existing pci_baseline.yaml (default: replace)

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

TOP=50
APPEND=0
RUN_DIR=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --run-dir) RUN_DIR="$2"; shift 2 ;;
    --top)     TOP="$2"; shift 2 ;;
    --append)  APPEND=1; shift ;;
    --help|-h) cat <<EOF
Usage: $0 [--run-dir <dir>] [--top <N>] [--append]

Generates stub baseline entries from the most recent scan's combined.sarif
and writes them to pci_baseline.yaml. Stubs require manual triage (see
docs/runbooks/pci-checkov.md).
EOF
      exit 0 ;;
    *) pci_log ERROR "unknown argument: $1"; exit 64 ;;
  esac
done

if [[ -z "$RUN_DIR" ]]; then
  RUN_DIR="$(ls -td "${PCI_REPO_ROOT}/.checkov"/*/ 2>/dev/null | head -1 || true)"
  if [[ -z "$RUN_DIR" ]]; then
    pci_log ERROR "no run dir found; pass --run-dir"
    exit 2
  fi
  RUN_DIR="${RUN_DIR%/}"
fi

combined_sarif="${RUN_DIR}/aggregate/combined.sarif"
if [[ ! -f "$combined_sarif" ]]; then
  pci_log ERROR "combined.sarif not found in ${RUN_DIR}/aggregate/ — run aggregate.py first"
  exit 2
fi

pci_log INFO "source: $combined_sarif"
pci_log INFO "target: $PCI_BASELINE_FILE"

# Build the entries JSON via python.
entries_json="$(python - "$combined_sarif" "$TOP" <<'PY'
import json, sys
from pathlib import Path
sarif = Path(sys.argv[1])
top_n = int(sys.argv[2])
data = json.loads(sarif.read_text(encoding="utf-8"))
seen = {}  # (check_id, resource) -> list of (project, env)
for run in data.get("runs", []):
    props = run.get("properties", {})
    project = props.get("pci_project", "")
    env = props.get("pci_env", "")
    for r in run.get("results", []):
        cid = r.get("ruleId", "UNKNOWN")
        # resource is typically empty here; use physical location as fallback
        locs = r.get("locations", [])
        uri = locs[0].get("physicalLocation", {}).get("artifactLocation", {}).get("uri", "") if locs else ""
        key = (cid, uri)
        seen.setdefault(key, []).append({"project": project, "env": env})
# Emit one entry per (check_id, uri) pair
out = []
for (cid, uri), hits in seen.items():
    out.append({
        "check_id": cid,
        "resource_pattern": uri or "*",
        "justification": "TBD",
        "compensating_control": "TBD",
        "owner": "TBD",
        "ticket_id": "TBD",
        "expires_on": "TBD",
        "first_seen": sorted({f"{h['project']}/{h['env']}" for h in hits}),
        "hit_count": len(hits),
    })
# Sort by hit_count desc
out.sort(key=lambda x: -x["hit_count"])
print(json.dumps(out, indent=2))
PY
)"

# If --append, merge with existing.
existing=""
if [[ $APPEND -eq 1 && -f "$PCI_BASELINE_FILE" ]]; then
  existing="$(python -c "import yaml, json; print(json.dumps(yaml.safe_load(open('$PCI_BASELINE_FILE'))['suppressions'] or []))")"
fi

# Write the new file. Preserve comment header.
python - "$PCI_BASELINE_FILE" "$entries_json" "$existing" "$APPEND" <<'PY'
import yaml, sys, json
from pathlib import Path
baseline_path = Path(sys.argv[1])
entries = json.loads(sys.argv[2])
existing = json.loads(sys.argv[3]) if sys.argv[3] else []
append = sys.argv[4] == "1"

# Build the merged suppr list
if append:
    seen = {(e["check_id"], e["resource_pattern"]) for e in existing}
    for e in entries:
        if (e["check_id"], e["resource_pattern"]) not in seen:
            existing.append(e)
            seen.add((e["check_id"], e["resource_pattern"]))
    suppr = existing
else:
    suppr = entries

# Read existing header (everything before the `suppressions:` key)
text = baseline_path.read_text(encoding="utf-8") if baseline_path.exists() else ""
header = ""
for line in text.splitlines():
    if line.startswith("suppressions:"):
        break
    header += line + "\n"
if not header.startswith("#"):
    header = (
        "# PCI baseline — repo-wide suppressions for known/accepted findings.\n"
        "# Generated by scanner/scan_pci_baseline_init.sh\n"
        "# See docs/runbooks/pci-checkov.md for triage workflow.\n"
        "#\n"
        "# Entries with TBD owner/ticket/expires_on DO NOT suppress findings.\n"
        "# Triage top-N by hit_count: populate justification, owner, ticket_id,\n"
        "# expires_on. The aggregator stops suppressing the entry if expires_on\n"
        "# is in the past OR owner == TBD.\n\n"
    )

data = {
    "version": 1,
    "verified_against": "2026-08-04",
    "suppressions": suppr,
}
baseline_path.write_text(header.rstrip() + "\n\n" + yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
print(f"wrote {len(suppr)} entries to {baseline_path}")
PY

pci_log INFO "baseline initialized; triage the top $TOP entries by hit_count"
